### ISSUE TITLE
IPFS integration

### ISSUE THREAD

**Issue by diasdavid** [pfrazee/beaker#2]
Hi @pfraze, it was great to chat at the #DWebSummit and getting to know about `beaker`.

Opening this issue so that we can continue our convo about IPFS integration and also invite other people in the community that might want to participate :)

Since beaker is an electron app, we can integrate either go-ipfs or js-ipfs, which in the short term, will give beaker's IPFS integration different properties, namely:

- Peer Routing + Content Routing (DHT) with go-ipfs
- WebRTC with js-ipfs.

Either way, we are standardizing the js-ipfs-api (HTTP-API client library) and js-ipfs core APi to expose the same calls, so that devs don't have to change any code when using a remote daemon or a in process daemon.

I still need to look into `beaker` code to get familiar with it, but meanwhile if you can give some lights on the integration should be done, it would be great. 

Meanwhile, here is a short list of things that we will be doing in our side:

- [ ] upgrade `ipfsd` to use bin-wrapper https://github.com/ipfs/js-ipfsd-ctl/issues/78 so that it can be added to any electron app independently of the architecture.
- [ ] finalize interface-ipfs-core https://github.com/ipfs/interface-ipfs-core

**Comment by pfraze** [comment]
@diasdavid great, thanks for opening this issue.

[This document explains the repo](https://github.com/pfraze/beaker/blob/master/build-notes.md). I think the background process is the right place to integrate the transport protocols, so that data can persist across navigations, and so we're not confined to WebRTC. So, go-ipfs seems like the right call.

Most of my dat integration's structure should be copyable for IPFS. There may be ways to reuse code btwn the protocol integrations, which will also pay off when we integrate webtorrent. No need to focus on that yet, though; let's just make it work, first.

After we have an `ipfs://` and `view-ipfs://` protocol, we can look into injecting the IPFS API into web pages.

Some info for reference:
 - [npm-go-ipfs](https://github.com/ipfs/npm-go-ipfs) ships prebuilt go-ipfs binaries, so devs should not need go installed to run beaker's build
 - When https://github.com/ipfs/js-ipfsd-ctl/issues/78 closes, [js-ipfsd-ctl](https://github.com/ipfs/js-ipfsd-ctl) will install the arch-appropriate ipfs binary on first execution. We'll need to hook into this and tell the user what's going on.
 - [js-ipfs-api](https://github.com/ipfs/js-ipfs-api) is how we'll interact with the go binary.

**Comment by pfraze** [comment]
@diasdavid @jbenet [this is what I have in mind for integration right now](https://gist.github.com/pfraze/e09dd58ed5a33040b830e902cc009d74). I shared it with the dat guys and they think it's doable on their end. I'm interested if you have technical or design issues to raise.

**Comment by pfraze** [comment]
I've hit an issue that'll need some thought.

Chromium (and thus Electron) have a concept of "standard" URLs. [You can read about them here](http://electron.atom.io/docs/api/protocol/#protocolregisterstandardschemesschemes).

To make electron's webviews handle paths correctly (in links, in imgs, etc) we want Electron to treat the folder hash as the domain. Then, paths like `/icon.png` will resolve as expected:

in `ipfs://QmTqDSxMH6xsKabqhBSeBVu89UmbF2Z1CbN4k4tT6Zhy8R/`, it'll resolve to...
`ipfs://QmTqDSxMH6xsKabqhBSeBVu89UmbF2Z1CbN4k4tT6Zhy8R/icon.png`

Here's the problem: the domain in standard URIs are case-insensitive. Once a protocol is registered as standard, chromium automatically runs toLowerCase on the path. In base58/64, this destroys information.

I've committed a basic integration. If you serve an `index.html` via ipfs, then remove `'ipfs'` from [this line](https://github.com/pfraze/beaker/blob/master/app/background-process.js#L23), you can open the file via `ipfs://{root-hash-that-includes-the-index.html}`. But, if you readd `'ipfs'` to the standard protocol registrations, you'll see the url bar automatically toLowerCase(), and the GET will fail.

Two possible solutions:

 1. Only use hex-encoded IPFS urls. This may not be super feasible, since the rest of the ecosystem is in base52+.
 2. Dont use chromium's standard-url protocols. This may work, but it won't be super easy. Maybe we can make the webviews work, as expected, through some combination of JS injected into the client, and request interception.

We might raise issues with electron, but that's an unlikely solution as well.

**Comment by pfraze** [comment]
Two small updates on my last post...
 - I managed to get things mostly working without the standard scheme. Paths were resolving better than I expected. So, that may not be too hard to handle.
 - I was pointed to https://github.com/ipfs/go-ipfs/issues/1678. Reading it now.

**Comment by pfraze** [comment]
![screen shot 2016-06-12 at 7 08 34 pm](https://cloud.githubusercontent.com/assets/1270099/15994747/4e16fe48-30d2-11e6-95cf-1c8cda05164a.png)

**Comment by davidar** [comment]
> I was pointed to ipfs/go-ipfs#1678. Reading it now.

@pfraze Long story short:

- use `/ipfs/Qm...` wherever possible
- if you *have* to use a URI, use `fs:/ipfs/Qm...`

**Comment by davidar** [comment]
> To make electron's webviews handle paths correctly (in links, in imgs, etc) we want Electron to treat the folder hash as the domain. Then, paths like /icon.png will resolve as expected

Absolute paths like `/icon.png` are strongly discouraged in IPFS, as they break on the HTTP gateway. Therefore it's generally safe to assume that websites on IPFS only use relative links, with the exception of absolute `/ipfs/Qm...` links.

**Comment by pfraze** [comment]
@diasdavid hey, I'd like to do a call with the IPFS team, to hear about the vision for IPFS browser. Do you think we could schedule one?

**Comment by nicola** [comment]
hey @pfraze I am really interested. A couple of weeks ago I attempted to make an ipfs-specific browser (specific to ipfs in every sense - even its components were on IPFS and makes it easier to be self-publish), I am happy to discuss design choices, I really love the approach in combining all the decentralized projects!

great work!

**Comment by pfraze** [comment]
@nicola right on, ping me on IRC sometime and we can chat

**Comment by diasdavid** [comment]
Can we do it Tuesday, 9am PDT, 5pm UTC?  @pfraze @nicola @jbenet

**Comment by pfraze** [comment]
Are those times ==? I think they maybe be off by an hour.

I can do Tuesday

**Comment by nicola** [comment]
I can do tuesday too

**Comment by diasdavid** [comment]
@pfraze you are right, fixed. Looking forward to chat today :) 

**9am PDT, 5pm WEST, 6pm UTC**

**Comment by pfraze** [comment]
Same. How should we get in touch? Google hangout?

**Comment by diasdavid** [comment]
Sent a cal invite with a Hangout URL :)

**Comment by pfrazee** [comment]
Now basically working. The code has been moved into https://github.com/pfrazee/beaker-plugin-ipfs. Give it a shot!

**Comment by Powersource** [comment]
@pfrazee that repo link is dead now. What's the status of this a year later?

**Comment by pfrazee** [comment]
Hey @Powersource, see my comment here https://github.com/beakerbrowser/beaker/issues/480#issuecomment-346865836
